{
 "title": "AAPL Stock Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Price",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "stock_current_price", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Price: Time Series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expr": "stock_current_price", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Low - Current - High",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expr": "stock_low_price", "legendFormat": "__auto" },
    { "expr": "stock_current_price", "legendFormat": "__auto" },
    { "expr": "stock_high_price", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Low Price",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "stock_low_price", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "High Price",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "stock_high_price", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Previous Close",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "stock_previous_close", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Dividend Yield",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "stock_dividend_yield", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Metrics Summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expr": "stock_current_price", "legendFormat": "__auto" },
    { "expr": "stock_high_price", "legendFormat": "__auto" },
    { "expr": "stock_low_price", "legendFormat": "__auto" },
    { "expr": "stock_dividend_yield", "legendFormat": "__auto" },
    { "expr": "stock_previous_close", "legendFormat": "__auto" }
   ]
  }
 ]
}